description: GRPO on decomposition training


environment:
  # image: amlt-sing/acpt-torch2.3.1-py3.10-cuda12.1-ubuntu22.04:20240918T133309423
  # image: lesong/nvidia-cuda-mujoco:v7
  # username: f2e15e898c154795b7a8c9a9d936095d
  # registry: f2e15e898c154795b7a8c9a9d936095d.azurecr.io
  registry: singularitybase.azurecr.io
  image: base/job/pytorch/acpt-2.2.1-py3.10-cuda12.1:20240312T225111416

  setup:
    - apt-get update -y
    - export PATH=$$HOME/.local/bin:$$PATH
    - export PYTHONPATH=$$HOME/.local/bin:$$PYTHONPATH
    - apt-get install -y cuda-toolkit-12.1
    - pip install --upgrade setuptools pip wheel
    - pip install nvidia-pyindex
    - pip install nvidia-cuda-runtime-cu12 nvidia-cuda-nvcc-cu12
    - export CUDA_HOME=/usr/local/cuda
    - export PATH=$$CUDA_HOME/bin:$$PATH
    - apt-get install git-lfs
    - pip install uv
    - uv venv openr1 --python 3.11 && source openr1/bin/activate && uv pip install --upgrade pip
    - uv pip install vllm==0.7.2
    - uv pip install setuptools && uv pip install flash-attn --no-build-isolation
    - GIT_LFS_SKIP_SMUDGE=1 uv pip install -e ".[dev]"
    - pip install python-dotenv
    # - pip install packaging
    # - pip install --upgrade bitsandbytes transformers peft accelerate datasets trl flash_attn

target:
  service: sing
  name: palisades03
  # name: msrresrchvc
  # name: msrresrchlab
  # name: msroctobasicvc
  workspace_name: rag-workspace-eastus

data:
  local_dir: data/
  remote_dir: data/

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: ./


# python experiment.py --seed 123 --env hopper --dataset medium-expert --eta 1.0 --grad_norm 9.0 --exp_name qt --save_path ./save/ --max_iters 100 --num_steps_per_iter 10000 --lr_decay --early_stop --k_rewards --use_discount --reprogram --desc_reg

jobs:
- name: dpo_test
  identity: managed
  submit_args:
    env:
      _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/e033d461-1923-44a7-872b-78f1d35a86dd/resourcegroups/RAG-WUS/providers/Microsoft.ManagedIdentity/userAssignedIdentities/rag-workspace-eastus-mi"
  sku: 40G8-A100-IB-NvLink
  # sku: 40G4
  # preemptible: true
  command:
    - accelerate launch --config_file recipes/accelerate_configs/fsdp.yaml --num_processes=8 src/open_r1/sft.py --config recipes/Qwen2.5-32B-Instruct/sft/config_demo.yaml
